name: Codecov
on: [push]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        # os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.10.5'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: "3.10.5"
    - name: Generate coverage report
      run: |
        pip install pytest
        pip install pytest-cov
        pip install hpyculator PySide6 pywin32 jpype1 numba  numpy
        pip install pytest-assume pytest-metadata pytest-html pytest-ordering pytest-rerunfailures pytest-sugar python-dateutil
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3.1.0
      with:
        # token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/reports/
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        files: ./coverage1.xml,./coverage2.xml
        flags: unittests
        name: codecov-umbrella
        # override_branch: dev
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true